name: Deploy to EC2

on:
  push:
    branches:
      - main  # Adjust if your default branch is named differently

jobs:
  deploy:
    name: Deploy to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Navigate to the application directory or clone the repository
            cd /path/to/your/application || git clone https://github.com/your-username/your-repo.git /path/to/your/application
            cd /path/to/your/application

            # Pull the latest changes
            git pull origin main

            # Install dependencies (adjust based on your application's stack)
            npm install  # For Node.js applications
            # pip install -r requirements.txt  # For Python applications

            # Restart the application (adjust based on your deployment strategy)
            pm2 restart all  # If using PM2 for process management
            # systemctl restart your-app.service  # If using systemd
          EOF
